### ISSUE TITLE
✖ Error: socket hang up

### ISSUE THREAD

**Issue by saulhardman** [niksy/sync-safari-reading-list-cli#1]
Hi @niksy, found your CLI tool via Google. Thanks for making it, it's a great idea and a simple tool to execute it :+1:

Having an issue running it as follows though: `sync-safari-reading-list -t TOKEN_HERE -k`

I can see via Little Snitch that the requests are made to the URLs (presumably to check they're still active) however it fails with this error message:

`✖ Error: socket hang up`

Any ideas what might be happening?

I'm on OS X 10.11.6 running Node v6.9.2.

**Comment by saulhardman** [comment]
Just to follow up; despite the error message this appears to have worked.

**Comment by niksy** [comment]
Hi @saulhardman!

I think this is related to request module which can’t successfully resolve one of the links you’ve provided for syncing. Since resolving and syncing is Promise based, any promise that fails will make every other promise that comes after it also to fail.

Have you managed to see which link creates problem and remove it from the list and then try again?

Maybe I could make loose option which ignores unsucessfully resolved links and just goes syncing other links?

**Comment by saulhardman** [comment]
Thanks for the response Ivan!

What would you say the expected behaviour is when resolving links?

My expectation is that it would resolve each link individually and throw an error specific to a single request if it fails. In which case it would continue to attempt to resolve the other links (as you described in reference to the 'loose' option).

I'm yet to find the link that's causing the issue, but I'll take a look at it again this afternoon :+1:

Just to note: I wasn't aware that it would carry out this link resolution step at all (from looking at both repositories). Would it be possible to add a note to the docs about this? I can do that if you'd like, just let me know.

**Comment by saulhardman** [comment]
I've identified the troublesome links after using the core module which gives better error messages:

```
(node:52517) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:52517) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://www.nytimes.com/2016/11/06/magazine/how-economic-gobbledygook-divides-us.html?_r=4
(node:52517) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:52517) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:52517) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:52517) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
```

It turns out this method of URL resolution doesn't play nice with NYT links (with query string parameters). I've manually added those links to Pinboard.

However, I'm now getting this error message:

```
(node:52737) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error while syncing with Pinboard: undefined
```

Any ideas @niksy? Thanks again for your help, I really appreciate it.

**Comment by niksy** [comment]
@saulhardman sorry for the late response, holiday and vacation time and all :)

So, I’ve made changes to the API module - `cleanUrls` option should now perform redirects and do the cleanup operation and it’s active by default.

CLI module (this module) has flag `--keep-original-urls` which won’t perform any cleanup or redirects so there won’t be any network requests performed other than syncing with Pinboard.

Does this seem okay to you?

As for notice on cleaning, it’s mentioned in API module but since there is now option for CLI module it’s also mentioned here and I’ve linked API module as related module to CLI module and vice versa, so there won’t be any confusion.

**Comment by saulhardman** [comment]
Hi @niksy, that's quite alright – I hope you had a nice break.

The changes sound great and I can confirm that they work perfectly too 🎉

Thanks again for taking the time to do this Ivan, I really appreciate it.
